import { Button, VerticalBox, HorizontalBox, SpinBox, GroupBox } from "std-widgets.slint";
import "./assets/Roboto_Condensed-Regular.ttf";

export global theme {
    out property <length> H : 30px;
    out property <length> ALLIANCE_NAME : 25px;
    out property <length> ALLIANCE_SOCRE : 50px;

    out property <percent> ALLIANCE_HEIGHT : 10%;
    out property <length> ALLIANCE_SCORE: 60px;
    out property <percent> TEAM_HEIGHT : 8%;
    out property <percent> SOCRE_HEIGHT : 10%;
}

export global vars {
    in-out property <int> matchNumber: 1;

    in-out property<string> red_team1;
    in-out property<string> red_team2;
    in-out property<string> blue_team1;
    in-out property<string> blue_team2;

    in-out property<string> red_team1_members;
    in-out property<string> red_team2_members;
    in-out property<string> blue_team1_members;
    in-out property<string> blue_team2_members;

    in-out property <int> max_matches: 10;

    in-out property <int> red_score: 0;
    in-out property <int> blue_score: 0;
}

export component ScoreWindow inherits Window {

    title: "CTEC In-House Challenge";

    default-font-family: "Roboto";

    width: 1536px;
    height: 864px;

    background: #000;

    HorizontalLayout {
        padding-top: 5px;
        padding-left: 5px;
        padding-right: 5px;
        padding-bottom: 5px;

        VerticalLayout {
            HorizontalLayout {
                spacing: 5px;
                Rectangle {
                    border-top-left-radius: 30px;
                    border-top-right-radius: 30px;
                    width: 33.333%;
                    height: theme.ALLIANCE_HEIGHT;
                    background: blue;
                    Text {
                        font-size: theme.H;
                        padding: 5px;
                        color: white;
                        text: "Blue Alliance";
                    }
                }
                Rectangle {
                    border-top-left-radius: 30px;
                    border-top-right-radius: 30px;
                    width: 33.333%;
                    height: theme.SOCRE_HEIGHT;
                    background: white;
                    Text {
                        font-size: theme.H;
                        color: black;
                        text: "Score Breakdown";
                    }
                }
                Rectangle {
                    border-top-left-radius: 30px;
                    border-top-right-radius: 30px;
                    width: 33.333%;
                    height: theme.ALLIANCE_HEIGHT;
                    background: red;
                    Text {
                        font-size: theme.H;
                        padding: 5px;
                        color: white;
                        text: "Red Alliance";
                    }
                }
            }

            HorizontalLayout {
                spacing: 5px;
                Rectangle {
                    width: 33.333%;
                    height: theme.TEAM_HEIGHT;
                    background: blue;
                    Text {
                        y: 1px;
                        font-size: theme.ALLIANCE_NAME;
                        padding: 5px;
                        color: white;
                        text: vars.blue_team1 + "    " + vars.blue_team2;
                    }
                    Text {
                        y: 40px;
                        font-size: theme.ALLIANCE_NAME - 7px;
                        padding: 5px;
                        color: white;
                        text: vars.blue_team1_members + "            " + vars.blue_team2_members;
                    }
                }
                Rectangle {
                    background: white;
                    width: 33.333%;
                    Text {
                        y: 1px;
                        color: black;
                        font-size: 45px;
                        text: "Match: " + vars.matchNumber;
                    }
                }
                Rectangle {
                    width: 33.333%;
                    height: theme.TEAM_HEIGHT;
                    background: red;
                    Text {
                        y: 1px;
                        font-size: theme.ALLIANCE_NAME;
                        padding: 5px;
                        color: white;
                        text: vars.red_team1 + "    " + vars.red_team2;
                    }
                    Text {
                        y: 40px;
                        font-size: theme.ALLIANCE_NAME - 7px;
                        padding: 5px;
                        color: white;
                        text: vars.red_team1_members + "            " + vars.red_team2_members;
                    }
                }
            }

            HorizontalLayout {
                spacing: 5px;
                Rectangle {
                    border-bottom-left-radius: 30px;
                    border-bottom-right-radius: 30px;
                    width: 33.333%;
                    height: 12%;
                    background: blue;
                    Text {
                        y: parent.y /2;
                        font-size: theme.ALLIANCE_SCORE;
                        padding: 1px;
                        color: white;
                        text: vars.blue_score;
                    }
                }
                Rectangle {
                    background: white;
                    width: 33.333%;
                    Text {
                        y: 1px;
                        color: black;
                        font-size: 45px;
                        text: "";
                    }
                }
                Rectangle {
                    border-bottom-left-radius: 30px;
                    border-bottom-right-radius: 30px;
                    width: 33.333%;
                    height: theme.TEAM_HEIGHT;
                    background: red;
                    Text {
                        y: parent.y /2;
                        font-size: theme.ALLIANCE_SCORE;
                        padding: 1px;
                        color: white;
                        text: vars.red_score;
                    }
                }
            }
        }
    }
}

export component ControlWindow inherits Window {
    //width: 800px;
    //height: 480px;
    background: gray;

    title: "CTEC - Control";
    //background: @image-url("./assets/StellerConstruction.png");
    icon: @image-url("./assets/StellerConstruction.png");
    Image {
        source: @image-url("./assets/StellerConstruction.png");
        image-fit: contain;
    }

    VerticalLayout {
        spacing: 10px;
        padding: 10px;
        Rectangle {
            opacity: 0.95;
            height: 25px;

            background: black;
            border-radius: 10px;
            border-width: 1px;
            border-color: darkblue;
            
            Text {text: "Control Window"; color: white;}
        }
        Rectangle {
            height: 55px;

            background: black;
            border-radius: 10px;
            border-width: 1px;
            border-color: darkblue;

            Text {text: "Match Managment " + vars.matchNumber; color: white; y: 3px;}
            HorizontalLayout {
                y: parent.height * 0.085;
                Rectangle {Text {text: "Match Number:";}}
                Rectangle {
                    width: 150px;
                    SpinBox {
                        maximum: vars.max_matches;
                        minimum: 1;
                        value <=> vars.matchNumber;
                    }
                }
            }
        }
        Rectangle {
            height: 120px;

            background: black;
            border-radius: 10px;
            border-width: 1px;
            border-color: darkblue;

            Text {text: "Auto Score"; color: white; y: 3px;}
            HorizontalLayout {
                y: parent.height * 0.085;
                padding: 20px;
                spacing: 20px;
                Rectangle {
                    border-radius: 10px;
                    border-width: 4px;
                    border-color: darkblue;
                    Text {
                        y: 10px;
                        text: "Blue";
                    }
                }
                Rectangle {
                    border-radius: 10px;
                    border-width: 4px;
                    border-color: darkred;
                    Text {
                        y: 10px;
                        text: "Red";
                    }
                }
            }
        }
    }
}